#!/groovy

pipeline{
  environment{
    JIRA_SITE="Jira-Evya"
  }
  agent any
  stages{
    stage('Test'){
      agent{
        docker{ 
          image 'qnib/pytest'
        }
      }
      steps{
        sh 'py.test -v --junit-xml test-reports/results.xml test.py'
      }
      post{
        success{
          comment("JEN-1", "Test Successfull! For results: ${env.absoluteUrl}")
        }
        failure{
          comment("JEN-1", "Test Failed! For results: ${env.absoluteUrl}")
        }
      }
    }
  }
}

void comment(jiraKey, commentText) {
  jiraAddComment idOrKey: jiraKey, comment: commentText
}
