#!/groovy

pipeline{
  environment{
    JIRA_SITE="Jira-Evya"
  }
  agent any
  stages{
    stage('Jira'){
      steps{
        comment("JEN-1", "My comment")
      }
    }
  }
}

void comment(jiraKey, commentBody) {
  def comment = [ body : commentBody ]
  jiraAddComment idOrKey: jiraKey, comment: comment
}
